version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    environment:
      MYSQL_DATABASE: 'artelligence_local'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '3333'
      MYSQL_HOSTNAME: 'db'
      AUTH_SECRET: 'super-project-secret'
    depends_on:
      - db
    volumes:
      - './api:/artelligence/api'
      - './common:/artelligence/common'
    ports:
      - 8080:8080

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'artelligence_local'
      MYSQL_ROOT_PASSWORD: '3333'
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbit-root'
      RABBITMQ_DEFAULT_PASS: '4444'
    ports:
      - 5672:5672
      - 15672:15672

  payment-service:
    container_name: payment-service
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile.dev
    environment:
      STRIPE_API_KEY: 'no-key'
    ports:
      - 8090:8090
    volumes:
      - './payment-service:/artelligence/payment-service'
      - './common:/artelligence/common'

  # imageprox
  #   image: willnorris/imageproxy
  #   hostname: imageproxy
  #   command: "-addr 0.0.0.0:80 -scaleUp true"
  #   ports:
  #     - "8099:80"
  #   user: root