FROM node:13.12.0-alpine as builder

ARG APP_WORKDIR=/artelligence/payment-service
ARG COMMON_WORKDIR=/artelligence/common

WORKDIR $APP_WORKDIR
COPY payment-service/package.json $APP_WORKDIR/package.json
COPY payment-service/package-lock.json $APP_WORKDIR/package-lock.json
RUN npm install

WORKDIR $COMMON_WORKDIR
COPY common/package.json $COMMON_WORKDIR/package.json
COPY common/package-lock.json $COMMON_WORKDIR/package-lock.json
RUN npm install

COPY /payment-service $APP_WORKDIR
COPY /common $COMMON_WORKDIR

EXPOSE 8090

WORKDIR $APP_WORKDIR
CMD ["npm", "start"]